services:
  ecosystem-workbench:
    image: ecosystemai/ecosystem-workbench:latest
    restart: unless-stopped
    environment:
      IP: http://localhost
      PORT: 3001
    networks:
      - ecosystem
    ports:
      - "80:80"
    depends_on: 
      - ecosystem-server
      - ecosystem-runtime-solo
      - ecosystem-runtime-solo2
      - ecosystem-runtime-solo3
      - ecosystem-notebooks
      - ecosystem-grafana

  ecosystem-server:
    image: ecosystemai/ecosystem-server:latest
    container_name: ecosystem-server
    restart: unless-stopped
    environment:
      CLOUD__: ecosystem-azure-marketplace
      MASTER_KEY: ${ECOSYSTEM_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      IP: http://localhost
      PORT: 3001
      RESET_USER: "true"
      NO_WORKBENCH: "true"
    volumes:
      - ${DATA_PATH}:/data
    networks:
      - ecosystem
    ports:
      - "3001:3001"
      - "54445:54445"
      - "54321:54321"

  ecosystem-runtime-solo:
    image: ecosystemai/ecosystem-runtime-solo:latest
    container_name: ecosystem-runtime
    restart: unless-stopped
    environment:
      MASTER_KEY: ${ECOSYSTEM_API_KEY}
      NO_MONGODB: 'true'
      FEATURE_DELAY: 800
      MONITORING_DELAY: 120
    volumes:
      - ${DATA_PATH}:/data
    networks:
      - ecosystem
    ports:
      - "8091:8091"
    depends_on: 
      - ecosystem-server

  ecosystem-runtime-solo2:
    image: ecosystemai/ecosystem-runtime-solo:latest
    container_name: ecosystem-runtime2
    restart: unless-stopped
    environment:
      MASTER_KEY: ${ECOSYSTEM_API_KEY}
      NO_MONGODB: 'true'
      FEATURE_DELAY: 800
      MONITORING_DELAY: 240
      PORT: 8092
    volumes:
      - ${DATA_PATH}:/data
    networks:
      - ecosystem
    ports:
      - "8092:8092"
    depends_on:
      - ecosystem-server

  ecosystem-runtime-solo3:
    image: ecosystemai/ecosystem-runtime-solo:latest
    container_name: ecosystem-runtime3
    restart: unless-stopped
    environment:
      MASTER_KEY: ${ECOSYSTEM_API_KEY}
      NO_MONGODB: 'true'
      FEATURE_DELAY: 800
      MONITORING_DELAY: 240
      PORT: 8093
    volumes:
      - ${DATA_PATH}:/data
    networks:
      - ecosystem
    ports:
      - "8093:8093"
    depends_on:
      - ecosystem-server


  ecosystem-notebooks:
    image: ecosystemai/ecosystem-notebooks:latest
    container_name: ecosystem-notebooks
    restart: unless-stopped
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ${DATA_PATH}/notebooks-users/notebooks:/app/Shared Projects
      - ${DATA_PATH}/notebooks-users:/home
      - ${DATA_PATH}:/data
    networks:
      - ecosystem
    ports:
      - "5111:8000"
      - "8010:8010"
    depends_on: 
      - ecosystem-server

  ecosystem-grafana:
    image: ecosystemai/ecosystem-grafana:latest
    container_name: ecosystem-worker-grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ALLOW_EMBEDDING: true
    networks:
      - ecosystem
    ports:
      - "3000:3000"
    depends_on: 
      - ecosystem-server

networks:
  ecosystem:
    external: true
